# Generated by Django 2.0.3 on 2018-03-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinname', models.CharField(max_length=5)),
                ('coinname_long', models.CharField(max_length=50)),
                ('priceBTC', models.FloatField(max_length=10)),
                ('priceUSD', models.FloatField(max_length=10)),
                ('priceETH', models.FloatField(max_length=10)),
                ('coin_type', models.CharField(choices=[('PRIV', 'Privacy'), ('NETW', 'Network'), ('GAME', 'Gaming'), ('PLAT', 'Platform'), ('PAYM', 'Payment')], max_length=50)),
                ('web_site', models.CharField(max_length=100)),
                ('coin_twitter', models.CharField(max_length=100)),
                ('coin_reddit', models.CharField(max_length=100)),
                ('coin_source', models.CharField(max_length=100)),
                ('coin_explorer', models.CharField(max_length=200)),
                ('coin_telegram', models.CharField(max_length=100)),
                ('coin_discord', models.CharField(max_length=100)),
                ('coin_tot_supply', models.IntegerField(max_length=20)),
                ('coin_circ_supply', models.IntegerField(max_length=20)),
                ('coin_market_cap', models.IntegerField(max_length=20)),
                ('coin_daily_volume', models.IntegerField(max_length=20)),
            ],
        ),
    ]
