# Generated by Django 2.0.3 on 2018-03-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_circ_supply',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_daily_volume',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_market_cap',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_tot_supply',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coinname',
            field=models.SlugField(),
        ),
    ]
