# Generated by Django 2.0.3 on 2018-03-25 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20180325_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='coinname',
            new_name='coin_name',
        ),
    ]
