# Generated by Django 2.0.3 on 2018-03-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20180325_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_discord',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_explorer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_reddit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_telegram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coinname_long',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='coin',
            name='web_site',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
